<?php
$html_email_text = "<html>";
$html_email_text .= "<head>";
$html_email_text .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"> ";
$html_email_text .= "<style type='text/css'>";
$html_email_text .= ".bordertop {display:block;width: 602px;height: 70px;border-top: 1px solid #979797;border-left: 1px solid #979797;border-right: 1px solid #979797;}";
$html_email_text .= ".borderbottom {border-left: 1px solid #979797;border-right: 1px solid #979797;border-bottom: 1px solid #979797;display:block;}";
$html_email_text .= "</style>";
$html_email_text .= "</head>";
$html_email_text .= "<body>";
$html_email_text .= "<table width=\"600\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
$html_email_text .= "  <tr> ";
$html_email_text .= "    <td class='bordertop'>";
$html_email_text .= " $Vartable1	  ";
$html_email_text .= "	    <tr> ";
$html_email_text .= "		 <td align=\"left\"><font face=\"verdana, arial\" size=\"-1\">$Varlogo</font></td>";
$html_email_text .= "		</tr>";
$html_email_text .= "	 </table>";
$html_email_text .= "	</td>";
$html_email_text .= "  </tr>";
$html_email_text .= "  <tr> ";
$html_email_text .= "    <td class='borderbottom'>";
$html_email_text .= "	 $Vartable2 " ;
$html_email_text .= "        <tr height=\"14\"> ";
$html_email_text .= "          <td height=\"14\">&nbsp;</td>";
$html_email_text .= "        </tr>";
$html_email_text .= "        <tr> ";
$html_email_text .= "          <td class=\"main\"><font face=\"verdana, arial\" size=\"-1\">$Vargendertext  ";
$html_email_text .= "          <br><br>$Vartextmail</font></td>";
$html_email_text .= "        </tr>";
$html_email_text .= " <tr height=\"14\"> ";
$html_email_text .= "   <td height=\"14\">&nbsp;</td> ";
$html_email_text .= " </tr></table>";
$html_email_text .= "<table width=\"600\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
$html_email_text .= " <tr height=\"14\">";
$html_email_text .= "   <td height=\"14\">&nbsp;</td>";
$html_email_text .= " </tr>";
$html_email_text .= "  <tr bgcolor=$trcolor> ";
$html_email_text .= "   <td>&nbsp;</td>";
$html_email_text .= "  </tr>";
$html_email_text .= "      </table></td>";
$html_email_text .= "  </tr>";
$html_email_text .= "</table>";
$html_email_text .= "</body>";
$html_email_text .= "</html>";
?>