<?php
$html_email_text = "<html>";
$html_email_text .= "<head>";
$html_email_text .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"> ";
$html_email_text .= "<style type='text/css'>";
$html_email_text .= "* {font-family: Verdana, Geneva, sans-serif; font-size:12px;}";
$html_email_text .= "a {color: #403735;text-decoration: none;}";
$html_email_text .= "h1 {font-size: 16px;}";
$html_email_text .= ".grijs {background: #ECECEC;width: 130px;height: 20px;padding: 5px 5px 5px 5px;}";
$html_email_text .= ".padding-left-5 {padding-left: 5px;}";
$html_email_text .= ".copyright {font-size: 11px; text-align: right;}";
$html_email_text .= ".footer {font-size: 11px;text-align: center;}";
$html_email_text .= "</style>";
$html_email_text .= "</head>";
$html_email_text .= "<body>";
$html_email_text .= "<table width=\"600\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
$html_email_text .= "<tr>";
$html_email_text .= "<td>";
$html_email_text .= "$Vartable1";
$html_email_text .= "<tr>";
$html_email_text .= "<td align=\"left\">$Varlogo</td>";
$html_email_text .= "</tr>";
$html_email_text .= "</table>";
$html_email_text .= "</td>";
$html_email_text .= "</tr>";
$html_email_text .= "<tr>";
$html_email_text .= "<td>";
$html_email_text .= "$Vartable2";
$html_email_text .= "<tr>";
$html_email_text .= "<td>$Vartext1</td>";
$html_email_text .= "</tr>";
$html_email_text .= "<tr> ";
$html_email_text .= "<td>$Vartext2</td>";
$html_email_text .= "</tr>";
$html_email_text .= "<tr>";
$html_email_text .= "<td class='copyright'>".$Varcopyright."</td>";
$html_email_text .= "</tr>";
$html_email_text .= "</table>";
$html_email_text .= "</tr>";
$html_email_text .= "<tr>";
$html_email_text .= "<td class='footer'>";
$html_email_text .= "$Varmailfooter";
$html_email_text .= "</td>";
$html_email_text .= "</tr>";
$html_email_text .= "</table>";
$html_email_text .= "</body>";
$html_email_text .= "</html>";
?>